services:
  # PostgreSQL Service
  postgres:
    image: postgres:17
    container_name: ticket-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ExpressJS Service
  express:
    build: .
    container_name: ticket-api
    depends_on:
      - postgres
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run dev"
    port:
      - "3000:3000"
    restart: unless-stopped

  # Caddy Reverse Proxy with HTTPS
  caddy:
    image: caddy:2
    container_name: ticket-caddy
    depends_on:
      - express
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
