name: Ticket
services:
  # PostgreSQL Service
  postgres:
    image: postgres:17
    container_name: ticket-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ExpressJS Service
  express:
    build: .
    container_name: ticket-api
    depends_on:
      - postgres
    env_file:
      - .env
    expose:
      - "${PORT}"
    command: sh -c "npx prisma migrate deploy && npm run dev"

# Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ticket-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express

volumes:
  postgres_data:
